# The workflow tests the RPP build for HOST backend and runs rpp-performancetests

name: CICD RPP HOST

on:
  pull_request:
    branches: [ ar/opt_resize_nearest_neighbor_host ]

jobs:

  build:
    name: Build validation and Performance check
    runs-on: [self-hosted, Linux, X64, cpu-gpu]
    steps:
    - name: Build validation - HOST
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        echo "PR#$PR_NUMBER is being verified."
        cd ~/dockerMount/abishek/github-workflows
        sudo rm -rf *
        git clone git@github.com:r-abishek/rpp.git
        cd rpp
        git checkout ar/opt_resize_nearest_neighbor_host
        git fetch origin pull/$PR_NUMBER/head:ar/pr
        git checkout ar/pr
        git log -3
        sudo docker exec abishek_workflows_do_not_use /bin/bash -c "cd /media/abishek/github-workflows/rpp; mkdir build; cd build; cmake -DBACKEND=OCL ..; sudo make -j20 install"
    - name: Performance check - HOST
      run: |
        sudo docker exec abishek_workflows_do_not_use /bin/bash -c "cd /media/abishek/github-workflows/rpp/utilities/rpp-performancetests/HOST_NEW; python3 generatePerformanceLogs.py --case_start 21 --case_end 21"
    - name: Compatibility check - HOST
      run: |
        echo "Skipping compatibility check."
        # echo "PR#$PR_NUMBER is being verified."
        # cd ~/dockerMount/abishek/github-workflows
        # git clone https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX.git
        # cd MIVisionX
        # git log -3
        # sudo docker exec abishek_workflows_do_not_use /bin/bash -c "cd /media/abishek/github-workflows/MIVisionX; mkdir build; cd build; cmake -DBACKEND=OCL ..; sudo make -j20 install"
    - name: Clean up
      run: |
        cd ~/dockerMount/abishek/github-workflows
        sudo rm -rf *