# The workflow tests the RPP build for OCL backend and runs rpp-performancetests

name: RPP OCL backend

on:
  # pull_request:
  #   branches: [ ar/testsuite ]
  push:
    branches: [ ar/testsuite ]

jobs:

  build:
    name: Build and performance tests
    runs-on: [self-hosted, Linux, X64, cpu-gpu]
    steps:
    - name: Running RPP build for OCL backend
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        echo "PR#$PR_NUMBER is being verified."
        cd ~/dockerMount/abishek/github-workflows
        sudo rm -rf *
        git clone git@github.com:r-abishek/rpp.git
        cd rpp
        git checkout ar/testsuite
        # git fetch origin pull/$PR_NUMBER/head:ar/pr
        # git checkout ar/pr
        git log -3
        sudo docker exec aa380859f77d /bin/bash -c "cd /media/abishek/github-workflows/rpp; mkdir build; cd build; cmake ..; sudo make -j20 install"
    - name: Running RPP OCL performance tests
      run: |
        sudo docker exec aa380859f77d /bin/bash -c "cd /media/abishek/github-workflows/rpp/utilities/rpp-performancetests/OCL_NEW; python3 generatePerformanceLogs.py"
    - name: Clean up
      run: |
        cd ~/dockerMount/abishek/github-workflows
        sudo rm -rf *